CREATE TABLE arbitraje (
    ARBITRAJE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    PRIMARY KEY(ARBITRAJE_ID)
);

INSERT INTO arbitraje(NOMBRE,APELLIDO)
VALUES('Oscar','Mejia Garcia');

INSERT INTO arbitraje(NOMBRE,APELLIDO)
VALUES('Fernando','Guerrero Ramírez');

INSERT INTO arbitraje(NOMBRE,APELLIDO)
VALUES('César Arturo','Ramos Palazuelos');

INSERT INTO arbitraje(NOMBRE,APELLIDO)
VALUES('Jorge Isaac','Rojas Castillo');


INSERT INTO arbitraje(NOMBRE,APELLIDO)
VALUES('Fernando','Hernandez Gomez');

INSERT INTO arbitraje(NOMBRE,APELLIDO)
VALUES('Brian Omar','Gonzalez Veles');

INSERT INTO arbitraje(NOMBRE,APELLIDO)
VALUES('Erick Yair','Miranda Galindo');

INSERT INTO arbitraje(NOMBRE,APELLIDO)
VALUES('Juan Andres','Esquivel Gonzalez');



INSERT INTO arbitraje(NOMBRE,APELLIDO)
VALUES('Daniel ','Quintero Huitrón');

INSERT INTO arbitraje(NOMBRE,APELLIDO)
VALUES('Jorge Antonio','Pérez Durán');

INSERT INTO arbitraje(NOMBRE,APELLIDO)
VALUES('Eduardo','Galvan Basulto');
