CREATE TABLE entrenador (
    ENTRENADOR_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    PRIMARY KEY(ENTRENADOR_ID)
);


INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Santiago','Solari');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Diego','Cocca');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Ariel','Holan');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Miguel','Herrera');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Jorge','Almada');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Rolando','Cristante');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Nicolas','Larcamon');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Juan','Reynoso');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Javier','Aguirre');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Marcelo','Michel');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Andres','Lillin');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Beñat','San Jose');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Pablo','Guede');

INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Paulo','Pezzolano');


INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Ricardo','Ferreti');


INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Leonardo','Ramos');


INSERT INTO entrenador (NOMBRE,APELLIDO)
VALUES('Sebastian','Mendez');
