CREATE TABLE equipo (
    EQUIPO_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE VARCHAR(50),
    PRIMARY KEY(EQUIPO_ID)
);

INSERT INTO equipo(NOMBRE)
VALUES('América');

INSERT INTO equipo(NOMBRE)
VALUES('Atlas');

INSERT INTO equipo(NOMBRE)
VALUES('León');

INSERT INTO equipo(NOMBRE)
VALUES('Tigres de la U.A.N.L.');

INSERT INTO equipo(NOMBRE)
VALUES('Santos Laguna');

INSERT INTO equipo(NOMBRE)
VALUES('Toluca');

INSERT INTO equipo(NOMBRE)
VALUES('FC Juárez');

INSERT INTO equipo(NOMBRE)
VALUES('Cruz Azul');

INSERT INTO equipo(NOMBRE)
VALUES('Rayados de Monterrey');

INSERT INTO equipo(NOMBRE)
VALUES('Guadalajara');

INSERT INTO equipo(NOMBRE)
VALUES('Universidad Nacional');

INSERT INTO equipo(NOMBRE)
VALUES('Club Atlético de San Luis');

INSERT INTO equipo(NOMBRE)
VALUES('Mazatlán FC');


INSERT INTO equipo(NOMBRE)
VALUES('Necaxa');


INSERT INTO equipo(NOMBRE)
VALUES('Pachuca');


INSERT INTO equipo(NOMBRE)
VALUES('Gallos Blancos de Querétaro');


INSERT INTO equipo(NOMBRE)
VALUES('Club Tijuana');


INSERT INTO equipo(NOMBRE)
VALUES('Puebla F.C.');
