
/* F U E R Z A S       B A S I C A S */


INSERT INTO jugador (NOMBRE,APELLIDO,WIMU_ALIAS,PESO,ESTATURA,NUMERO_JUGADOR,FECHA_NACIMIENTO,
          ID_POSICION_PRINCIPAL,ID_PAIS_NACIMIENTO,ID_NACIONALIDAD,
          ID_CATEGORIA,ID_EQUIPO,ZURDO)
VALUES('Alberto','Herrera Rodríguez','ALBERTO HERRERA',75,1.75,198,TO_DATE('2001/02/23 12:00:00','yyyy/mm/dd hh24:mi:ss'),
(SELECT POSICION_ID FROM posicion WHERE NOMBRE = 'Volante'),
(SELECT PAIS_ID FROM pais WHERE NOMBRE = 'Mexico'),
(SELECT NACIONALIDAD_ID FROM nacionalidad WHERE NOMBRE = 'Mexicano'),2,
(SELECT EQUIPO_ID FROM equipo WHERE NOMBRE = 'Puebla F.C.'),1
);


INSERT INTO jugador (NOMBRE,APELLIDO,WIMU_ALIAS,PESO,ESTATURA,NUMERO_JUGADOR,FECHA_NACIMIENTO,
          ID_POSICION_PRINCIPAL,ID_PAIS_NACIMIENTO,ID_NACIONALIDAD,
          ID_CATEGORIA,ID_EQUIPO)
VALUES('Dylan Rafael','Torres Muratalla','DYLAN TORRES',56,1.66,210,TO_DATE('2004/02/03 12:00:00','yyyy/mm/dd hh24:mi:ss'),
(SELECT POSICION_ID FROM posicion WHERE NOMBRE = 'Volante'),
(SELECT PAIS_ID FROM pais WHERE NOMBRE = 'Mexico'),
(SELECT NACIONALIDAD_ID FROM nacionalidad WHERE NOMBRE = 'Mexicano'),2,
(SELECT EQUIPO_ID FROM equipo WHERE NOMBRE = 'Puebla F.C.')
);


INSERT INTO jugador (NOMBRE,APELLIDO,WIMU_ALIAS,PESO,ESTATURA,NUMERO_JUGADOR,FECHA_NACIMIENTO,
          ID_POSICION_PRINCIPAL,ID_PAIS_NACIMIENTO,ID_NACIONALIDAD,
          ID_CATEGORIA,ID_EQUIPO)
VALUES('Cristian Jassiel','Mares Sánchez','CRISTIAN MARES',72,1.78,207,TO_DATE('2004/09/12 12:00:00','yyyy/mm/dd hh24:mi:ss'),
(SELECT POSICION_ID FROM posicion WHERE NOMBRE = 'Media Punta'),
(SELECT PAIS_ID FROM pais WHERE NOMBRE = 'Mexico'),
(SELECT NACIONALIDAD_ID FROM nacionalidad WHERE NOMBRE = 'Mexicano'),2,
(SELECT EQUIPO_ID FROM equipo WHERE NOMBRE = 'Puebla F.C.')
);


INSERT INTO jugador (NOMBRE,APELLIDO,WIMU_ALIAS,PESO,ESTATURA,NUMERO_JUGADOR,FECHA_NACIMIENTO,
          ID_POSICION_PRINCIPAL,ID_PAIS_NACIMIENTO,ID_NACIONALIDAD,
          ID_CATEGORIA,ID_EQUIPO)
VALUES('Emilio','Martínez González','EMILIO  MARTINEZ',78,1.79,204,TO_DATE('2003/03/02 12:00:00','yyyy/mm/dd hh24:mi:ss'),
(SELECT POSICION_ID FROM posicion WHERE NOMBRE = 'Carrilero'),
(SELECT PAIS_ID FROM pais WHERE NOMBRE = 'Mexico'),
(SELECT NACIONALIDAD_ID FROM nacionalidad WHERE NOMBRE = 'Mexicano'),2,
(SELECT EQUIPO_ID FROM equipo WHERE NOMBRE = 'Puebla F.C.')
);
