CREATE TABLE nacionalidad (
    NACIONALIDAD_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE VARCHAR2(50),
    PRIMARY KEY(NACIONALIDAD_ID)
);


INSERT INTO nacionalidad (NOMBRE)
VALUES('Paraguayo');


INSERT INTO nacionalidad (NOMBRE)
VALUES('Mexicano');


INSERT INTO nacionalidad (NOMBRE)
VALUES('Argentino');


INSERT INTO nacionalidad (NOMBRE)
VALUES('Uruguayo');


INSERT INTO nacionalidad (NOMBRE)
VALUES('Brasileño');


INSERT INTO nacionalidad (NOMBRE)
VALUES('Ghanés');


INSERT INTO nacionalidad (NOMBRE)
VALUES('Chileno');


INSERT INTO nacionalidad (NOMBRE)
VALUES('Venezolano');
