BEGIN
    if ((:P15_ID_SEGMENTO_CORPORAL > 0 ) and (:P15_ID_STC > 0)) THEN
        insert into AF_SESION_TERAPIA_CONSULTORIO(ID_SESION_FISIOTERAPIA,ID_GRUPO_MUSCULAR,ID_SUBTIPO_TERAPIA_CONSULTORIO,FECHA_MODIFICACION)values(:P15_ID_SESION_FISIOTERAPIA,:P15_ID_SEGMENTO_CORPORAL,:P15_ID_STC,(SELECT SYSDATE - (5/24) FROM  dual));
    end if;

    if ((:P15_SEGMENTO2_CORPORAL > 0 ) and (:P15_S2TC > 0) ) THEN
        insert into AF_SESION_TERAPIA_CONSULTORIO(ID_SESION_FISIOTERAPIA,ID_GRUPO_MUSCULAR,ID_SUBTIPO_TERAPIA_CONSULTORIO,FECHA_MODIFICACION)values(:P15_ID_SESION_FISIOTERAPIA,:P15_SEGMENTO2_CORPORAL,:P15_S2TC,(SELECT SYSDATE - (5/24) FROM  dual));
    end if;


    if ((:P15_SEGMENTO3_CORPORAL > 0 ) and (:P15_S3TC > 0) ) THEN
        insert into AF_SESION_TERAPIA_CONSULTORIO(ID_SESION_FISIOTERAPIA,ID_GRUPO_MUSCULAR,ID_SUBTIPO_TERAPIA_CONSULTORIO,FECHA_MODIFICACION)values(:P15_ID_SESION_FISIOTERAPIA,:P15_SEGMENTO3_CORPORAL,:P15_S3TC,(SELECT SYSDATE - (5/24) FROM  dual));
    end if;

    if ((:P15_SEGMENTO4_CORPORAL > 0 ) and (:P15_S4TC > 0) ) THEN
        insert into AF_SESION_TERAPIA_CONSULTORIO(ID_SESION_FISIOTERAPIA,ID_GRUPO_MUSCULAR,ID_SUBTIPO_TERAPIA_CONSULTORIO,FECHA_MODIFICACION)values(:P15_ID_SESION_FISIOTERAPIA,:P15_SEGMENTO4_CORPORAL,:P15_S4TC,(SELECT SYSDATE - (5/24) FROM  dual));
    end if;


    if ((:P15_SEGMENTO5_CORPORAL > 0 ) and (:P15_S5TC > 0) ) THEN
        insert into AF_SESION_TERAPIA_CONSULTORIO(ID_SESION_FISIOTERAPIA,ID_GRUPO_MUSCULAR,ID_SUBTIPO_TERAPIA_CONSULTORIO,FECHA_MODIFICACION)values(:P15_ID_SESION_FISIOTERAPIA,:P15_SEGMENTO5_CORPORAL,:P15_S5TC,(SELECT SYSDATE - (5/24) FROM  dual));
    end if;

    if ((:P15_SEGMENTO6_CORPORAL > 0 ) and (:P15_S6TC > 0) ) THEN
        insert into AF_SESION_TERAPIA_CONSULTORIO(ID_SESION_FISIOTERAPIA,ID_GRUPO_MUSCULAR,ID_SUBTIPO_TERAPIA_CONSULTORIO,FECHA_MODIFICACION)values(:P15_ID_SESION_FISIOTERAPIA,:P15_SEGMENTO6_CORPORAL,:P15_S6TC,(SELECT SYSDATE - (5/24) FROM  dual));
    end if;

    if ((:P15_SEGMENTO7_CORPORAL > 0 ) and (:P15_S7TC > 0) ) THEN
        insert into AF_SESION_TERAPIA_CONSULTORIO(ID_SESION_FISIOTERAPIA,ID_GRUPO_MUSCULAR,ID_SUBTIPO_TERAPIA_CONSULTORIO,FECHA_MODIFICACION)values(:P15_ID_SESION_FISIOTERAPIA,:P15_SEGMENTO7_CORPORAL,:P15_S7TC,(SELECT SYSDATE - (5/24) FROM  dual));
    end if;

    if ((:P15_SEGMENTO8_CORPORAL > 0 ) and (:P15_S8TC > 0) ) THEN
        insert into AF_SESION_TERAPIA_CONSULTORIO(ID_SESION_FISIOTERAPIA,ID_GRUPO_MUSCULAR,ID_SUBTIPO_TERAPIA_CONSULTORIO,FECHA_MODIFICACION)values(:P15_ID_SESION_FISIOTERAPIA,:P15_SEGMENTO8_CORPORAL,:P15_S8TC,(SELECT SYSDATE - (5/24) FROM  dual));
    end if;

    if ((:P15_SEGMENTO9_CORPORAL > 0 ) and (:P15_S9TC > 0) ) THEN
        insert into AF_SESION_TERAPIA_CONSULTORIO(ID_SESION_FISIOTERAPIA,ID_GRUPO_MUSCULAR,ID_SUBTIPO_TERAPIA_CONSULTORIO,FECHA_MODIFICACION)values(:P15_ID_SESION_FISIOTERAPIA,:P15_SEGMENTO9_CORPORAL,:P15_S9TC,(SELECT SYSDATE - (5/24) FROM  dual));
    end if;
END;
