"""
    AMAURY ESCOTO
    ANTONY SILVA
    CHRISTIAN TABO
    CLIFFORD ABOAGYE
    DANIEL ALVAREZ
    DANIEL AGUILAR
    DIEGO DE BUEN
    DIETER VILLALPANDO
    EMANUEL GULARTE
    FERNANDO ARISTEGUIETA
    GEORGE CORRAL
    GUILLERMO MARTÍNEZ
    GUSTAVO FERRAREIS
    ISRAEL REYES
    IVAN RODRIGUEZ
    IVO VAZQUEZ
    JAVIER SALAS
    JHORY CELAYA
    JUAN SEGOVIA
    LUCAS MAIA
    MAXIMILIANO ARAÚJO
    PABLO PARRA
    RAMON JUAREZ
    RAUL CASTILLO
    SEBASTIAN MEDELLIN
"""
class Alias():

    def get_alias(players_hash_table):
        for i in players_hash_table

            if i == ""
