CREATE TABLE grado_lesion_medica (
    GRADO_LM_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    GRADO NUMBER,
    PRIMARY KEY(GRADO_LM_ID)
);


INSERT INTO grado_lesion_medica(GRADO)
VALUES(1);



INSERT INTO grado_lesion_medica(GRADO)
VALUES(2);



INSERT INTO grado_lesion_medica(GRADO)
VALUES(3);
