CREATE TABLE subtipo_lesion_medica (
    SUBTIPO_LESION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE_SUBTIPO_LESION  VARCHAR2(30),
    ID_GRADO NUMBER,
    ID_TIPO_LESION NUMBER NOT NULL,

    PRIMARY KEY(SUBTIPO_LESION_ID),
    FOREIGN KEY(ID_GRADO) REFERENCES grado_lesion_medica(GRADO_LM_ID),
    FOREIGN KEY(ID_TIPO_LESION) REFERENCES tipo_lesion_medica(TIPO_LESION_ID)

);


INSERT INTO subtipo_lesion_medica(NOMBRE_SUBTIPO_LESION,ID_TIPO_LESION)
VALUES('contusion',
        (SELECT TIPO_LESION_ID FROM tipo_lesion_medica WHERE NOMBRE_TIPO_LESION = 'lesion muscular'));


INSERT INTO subtipo_lesion_medica(NOMBRE_SUBTIPO_LESION,ID_TIPO_LESION)
VALUES('calambre',
  (SELECT TIPO_LESION_ID FROM tipo_lesion_medica WHERE NOMBRE_TIPO_LESION = 'lesion muscular'));


INSERT INTO subtipo_lesion_medica(NOMBRE_SUBTIPO_LESION,ID_TIPO_LESION)
VALUES('contractura',
  (SELECT TIPO_LESION_ID FROM tipo_lesion_medica WHERE NOMBRE_TIPO_LESION = 'lesion muscular'));






  INSERT INTO subtipo_lesion_medica(NOMBRE_SUBTIPO_LESION,ID_TIPO_LESION)
  VALUES('entesitis',
          (SELECT TIPO_LESION_ID FROM tipo_lesion_medica WHERE NOMBRE_TIPO_LESION = 'lesion tendinosa'));


  INSERT INTO subtipo_lesion_medica(NOMBRE_SUBTIPO_LESION,ID_TIPO_LESION)
  VALUES('tendinitis',
    (SELECT TIPO_LESION_ID FROM tipo_lesion_medica WHERE NOMBRE_TIPO_LESION = 'lesion tendinosa'));


  INSERT INTO subtipo_lesion_medica(NOMBRE_SUBTIPO_LESION,ID_TIPO_LESION)
  VALUES('tendonitis',
    (SELECT TIPO_LESION_ID FROM tipo_lesion_medica WHERE NOMBRE_TIPO_LESION = 'lesion tendinosa'));






INSERT INTO subtipo_lesion_medica(NOMBRE_SUBTIPO_LESION,ID_TIPO_LESION)
VALUES('fractura',
        (SELECT TIPO_LESION_ID FROM tipo_lesion_medica WHERE NOMBRE_TIPO_LESION = 'lesion osea'));


INSERT INTO subtipo_lesion_medica(NOMBRE_SUBTIPO_LESION,ID_TIPO_LESION)
VALUES('fisura',
  (SELECT TIPO_LESION_ID FROM tipo_lesion_medica WHERE NOMBRE_TIPO_LESION = 'lesion osea'));


INSERT INTO subtipo_lesion_medica(NOMBRE_SUBTIPO_LESION,ID_TIPO_LESION)
VALUES('contusion',
  (SELECT TIPO_LESION_ID FROM tipo_lesion_medica WHERE NOMBRE_TIPO_LESION = 'lesion osea'));
