CREATE TABLE tipo_lesion_medica (
    TIPO_LESION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE_TIPO_LESION  VARCHAR(30),

    PRIMARY KEY(TIPO_LESION_ID)
);


INSERT INTO tipo_lesion_medica(NOMBRE_TIPO_LESION)
VALUES('lesion muscular');


INSERT INTO tipo_lesion_medica(NOMBRE_TIPO_LESION)
VALUES('lesion tendinosa');


INSERT INTO tipo_lesion_medica(NOMBRE_TIPO_LESION)
VALUES('lesion osea');
